version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Installing SBT...
      - echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
      - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
      - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
      - apt-get update
      - apt-get install -y sbt
  pre_build:
    commands:
      - mkdir -p /sources/
      - cp -a ${CODEBUILD_SRC_DIR}/. /sources
  build:
    commands:
      - echo Build started on `date`
      - cd /source
      - sbt "project crawler" test assembly

artifacts:
  files:
    - target/scala-2.13/crawler.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.ivy2/cache/**/*'
    - '/root/.cache/**/*'
    - 'target/**/*'